### ISSUE TITLE
Some games I own don't show up on the games available to install

### ISSUE THREAD

**Issue by Sloneborg** [ebenbruyns/junkstore#36]
I noticed that not all the games I own on epic is showing up as games I owned. 

One example is I own Dead Space Remake but it doesn't show up like I own the game so I can install it.

My steam deck is on os version 3.5.19 and using Junk Store 1.0

**Comment by mrsjunkrunner** [comment]
> I have the same issue with Farming Simulator 22

hey could install v1.1 from the testing store and let us know how you get on.

**Comment by wian007** [comment]
Yes that worked :D thank you

**Comment by mrsjunkrunner** [comment]
fixed with new version

**Comment by kbhavsar2** [comment]
This is still happening to me. I am on Steam OS version 3.5.19 and Junk Store 1.1.2-a9ad568. I tried on the stable build first and then tried your testing channel suggestion for the fix but still missing games.  Notably any Star Wars games (STAR WARS Jedi: Survivor™ , STAR WARS Jedi: Fallen Order Standard Edition , STAR WARS™: Squadrons , STAR WARS™ Battlefront™ II: Celebration Edition)

Also tried the refresh konsole command from your troubleshooting guide with no luck.

**Comment by mrsjunkrunner** [comment]
> This is still happening to me. I am on Steam OS version 3.5.19 and Junk Store 1.1.2-a9ad568. I tried on the stable build first and then tried your testing channel suggestion for the fix but still missing games. Notably any Star Wars games (STAR WARS Jedi: Survivor™ , STAR WARS Jedi: Fallen Order Standard Edition , STAR WARS™: Squadrons , STAR WARS™ Battlefront™ II: Celebration Edition)
> 
These are all EA games which are not supported yet in Junk-Store. These games and this launcher (as well as Ubisoft) are notoriously difficult to get working. This is due to EA making updates and changes that keep breaking things for solutions.

In future please don't comment on closed issues; if they are closed then they are closed for a reason (i.e. resolved, or won't fix, etc.) If you have an issue then, yes you should create a new issue entry.

I won't reopen this issue, as your issue is not the same as the OP's. I also believe that this will answer you question as well, so it will remain closed. This also is not actually a bug.
